# Project information
site_name: Krateo PlatformOps
site_url: https://docs.krateo.io
site_author: Krateo PlatformOps

# Repository
repo_name: krateo
repo_url: https://github.com/krateoplatformops/krateo-docs
edit_uri: edit/master/docs
docs_dir: docs

# Navigation
nav:
  - Overview: README.md
  - Glossary: glossary.md
  - Requirements: requirements.md
  - How to install Krateo PlatformOps: how-to-install.md
  - Krateo CLI:
      - The Krateo CLI tool: cli/cli-overview.md
      - Installing the Krateo CLI: cli/cli-install.md
      - Using Krateo CLI: cli/cli-using.md
      - Krateo CLI 'init' command workflow: cli/cli-init-workflow.md
  - App:
      - Overview: app/app-overview.md
      - Dashboard: app/app-dashboard.md
      - Deployments: app/app-deployments.md
      - Templates: app/app-templates.md
      - Packages: app/app-packages.md
      - Register: app/app-register.md
      - Settings: app/app-settings.md
## DO NOT CHANGE BELOW THIS LINE

# Copyright
# TBD

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    # - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.indexes
  palette:
    scheme: default
    primary: blue
    accent: blue

# Plugins
plugins:
  - search

# Customization
# TBD

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
